apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    # this refers the one present under the template metadata labels key value
    component: server
  ports:
    - port: 5000
      targetPort: 5000
